dependencies:
  - role: nginx-proxy
    domain: andrefreitas.pt
    proxy_pass: http://localhost:4001
    extra_server_configs: |
      location /git {
        proxy_pass http://localhost:4003;
      }
