- name: nginx configuration
  template: src=nginx.conf.j2 dest="/etc/nginx/sites-available/{{domain}}.conf"
  notify:
    - reload nginx

- name: enable website
  file: state=link src=/etc/nginx/sites-available/{{domain}}.conf dest=/etc/nginx/sites-enabled/{{domain}}.conf
  notify:
    - reload nginx
