- name: cgit container
  docker_container:
    name: cgit
    image: docker.andrefreitas.pt/cgit
    restart_policy: always
    pull: true
    ports:
      - "4003:80"
    volumes:
      - "/home/git:/mnt/git"
