- apt: update_cache=yes
- apt: name=htop

- name: Sets the hostname
  hostname: name={{ inventory_hostname }}

- name: Creates admin group
  group: name=admin system=yes

- name: Creates users
  user: name={{ item.name }} group={{ item.group }} shell={{ item.shell }}
  with_items: users

- name: Adds SSH Keys
  authorized_key: user={{ item.name }} key="{{ lookup('file', item.key ) }}"
  with_items: users

- name: Copy sudoers file for safety
  command: cp -f /etc/sudoers /etc/sudoers.tmp

- name: Create sudoers file backup
  command: cp -f /etc/sudoers /etc/sudoers.bak

- name: make sure we can sudo as admin group
  lineinfile: dest=/etc/sudoers.tmp state=present regexp='^%admin' line='%admin ALL=(ALL) NOPASSWD:ALL'

- name: also make sure ssh-agent works via sudo
  lineinfile: dest=/etc/sudoers.tmp state=present regexp='^Defaults env_keep\+\=SSH_AUTH_SOCK' line='Defaults env_keep+=SSH_AUTH_SOCK'

- name: Final sudoers file check
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
