- name: Setup GPG Key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Setup Debian Repository
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-{{ansible_distribution_release}} main"

- name: Install Docker
  apt: name=docker-engine

- name: Install Docker Py
  pip: name=docker-py

- name: Create Directory for volumes
  file: state=directory dest=/srv/containers

- name: Create Directory for settings
  file: state=directory dest=/srv/settings

- name: Login to docker.andrefreitas.pt
  docker_login:
    registry: "{{ docker_registry.domain}}"
    username: "{{ docker_registry.username }}"
    password: "{{ docker_registry.password }}"
    email: "{{ docker_registry.email }}"
    reauth: yes
