- name: Setup GPG Key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Setup Debian Repository
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-{{ansible_distribution_release}} main"

- name: Install Docker
  apt: name=docker-engine

- name: Install Docker Py
  pip: name=docker-py
