- name: Basic auth credentials
  copy: content="{{ docker_registry.htpasswd }}" dest=/srv/settings/registry_htpasswd
  notify: restart registry

- name: Registry container
  docker:
    state: reloaded
    restart_policy: always
    name: registry
    image: registry:2.5.1
    net: bridge
    ports:
      - "4002:5000"
    volumes:
      - /srv/containers/registry/:/var/lib/registry
      - /etc/letsencrypt/live/{{docker_registry.domain}}/fullchain.pem:/ssl/fullchain.pem
      - /etc/letsencrypt/live/{{docker_registry.domain}}/privkey.pem:/ssl/privkey.pem
      - /srv/settings/registry_htpasswd:/htpasswd/docker
    env:
      REGISTRY_HTTP_TLS_CERTIFICATE: /ssl/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /ssl/privkey.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /htpasswd/docker
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_SECRET: "{{ docker_registry.http_secret }}"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
